id: I32292BBE
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:05:09.334805
last_modified: 2023-02-09 15:05:09.334985
source_metadata:
  title: 'MSV 1,05: Carmavastu'
  language: sa
bases:
  DA28:
    base_file: DA28.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
